version: '3'
services:
  nginx:
    build: ./nginx
    ports:
        - '80:80'
    depends_on:
        - php-fpm
    links:
        - php-fpm
    volumes:
        - ../sources/:/var/www/html
        - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./php-fpm
    depends_on:
        - mysql
    links:
        - mysql
    volumes:
        - ../sources/:/var/www/html
        - ./php-fpm/config/php.ini:/etc/php.ini
        - ./php-fpm/config/php-fpm.conf:/etc/php-fpm.conf
        - ./php-fpm/config/www.conf:/etc/php-fpm.d/www.conf
        - ./php-fpm/config/15-xdebug.ini:/etc/php.d/15-xdebug.ini
  mysql:
    image: mysql:8.0.16
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root         #ここにroot用のパスワードを記載
      MYSQL_DATABASE: myblog_db         #ここにデータベースを記載
      MYSQL_USER: myblog_user           #ここにユーザ名を記載
      MYSQL_PASSWORD: myblog_password   #ここにユーザ用パスワードを記載
